### ISSUE TITLE
NEW TERM: orthographicNotes

### ISSUE THREAD

**Issue by ptsefton** [Language-Research-Technology/language-data-commons-vocabs#29]
Needed by PARADISEC 

collection | orthographic_notes |   | 1:1 | Notes on the orthography used in the metadata. The writing conventions that need to be understood to read the metadata. | Contains some unicode characters in line with IPA symbols, such as tlda underneath for creaky voice, and bar-i for high-mid vowel. |   | <mods:note type="orthographicNotes">Uses British English spelling conventions.</mods:note> | Yep - lets import that term into LDAC terms | https://www.loc.gov/standards/mods/mods-notes.html

**Comment by rosanna-smith** [comment]
Other terms to add from meeting:
- comment
- itemLocation

In line 4 of [the spreadsheet](https://docs.google.com/spreadsheets/d/1tcXhXFjooWH76zw1V-btYX-XXhI9toSk2pGETFCU13g/edit?gid=0#gid=0) that's listed as a term to add, but MediaObject is crossed out, so what's the term we should add here?

**Comment by ptsefton** [comment]
schema:material

**Comment by rosanna-smith** [comment]
Using orthographic notes as an example, is this the type of entry that should be added for this and the other terms to ontology/ro-crate-metadata.json? Need to check the correct inDefinedTermSet and sameAs for this and the other items to add.

```
      "@id": "https://w3id.org/ldac/terms#OrthographicNotes",
      "@type": "DefinedTerm",
      "name": "OrthographicNotes",
      "description": "Notes on the orthography used in the metadata. The writing conventions that need to be understood to read the metadata.",
      "inDefinedTermSet": {
        "@id": "https://w3id.org/ldac/terms#DerivedMaterialTypeTerms"
      },
      "sameAs": {
        "@id": "TODO"
```

**Comment by rosanna-smith** [comment]
@ptsefton some follow-up questions on the added terms:
- Do `itemLocation` and `comment` need domainIncludes and rangeIncludes?
- Should `OrthographicNotes` have a sameAs?
- make ont outputs a vocabulary.csv file - is that needed?

**Comment by ptsefton** [comment]
Yes. We need domainIncludes and rangeIncludes on all props.  itemLocation would have domain RepositoryObject and range Place, Organization and comment has domain Thing (ie evertyhing) 

I think we should shelve OrthographicNotes for now -- it could be added as a comment, or PARADISEC can come up with their own solution we can adpot later.

The CSV file is not really needed - that was used as part of an RO-Crate workflow for publishing vocabs

**Comment by rosanna-smith** [comment]
Thanks - I'll remove OrthographicNotes for now. Would comment also have Place and Organization as range?
Is there a schema.org link for RepositoryObject or should I be looking for that elsewhere?

**Comment by rosanna-smith** [comment]
Most of the domainIncludes are http://schema.org/CreativeWork

**Comment by rosanna-smith** [comment]
Not adding orthographicNotes currently, but itemLocation is included now.
